### ISSUE TITLE
Bundle and Example in parallel folders

### ISSUE THREAD

**Issue by mflux** [thgh/rollup-plugin-serve#1]
In my scenario...

![screenshot 2017-03-29 12 00 14](https://cloud.githubusercontent.com/assets/1041360/24471819/377679ea-1478-11e7-8d36-a1e3500ea124.png)

I want to serve `examples` but my module is built into `build` because this is a lib that people will consume.

However, the served example doing
    <script src="../build/lib.js"></script>

Will not serve correctly. What's the best way to handle this situation? Is there a copy operation? Can serve perform relative paths or does that breach security?

**Comment by thgh** [comment]
You could serve `./` and then visit `http://localhost:10001/examples`. Does that work for you?

**Comment by mflux** [comment]
I was hoping to place _only_ project files in ./ and _only_ example files (html, css, additional js) in ./examples.

I suppose I could place an index.html on project root but it just seems really messy. How do other projects handle this?

**Comment by thgh** [comment]
You don't need html in `./`, it's a matter of navigating to an html file in a subfolder.
Adding `./index.html` with a meta tag redirect to `/examples/index.html` is optional but can be handy.

I suppose it's possible to add configuration to serve from two directories, but it seems to me that that is not a common practice. So I would prefer to keep the plugin simple.

**Comment by jdonaldson10** [comment]
I have exactly the same use case as @mflux in a few of my projects. Looking at other module bundlers/task runners this type of setup is seems pretty supported by allowing an array of values for their `contentBase` equivalent.

From some quick searching I can see support in:
- [webpack dev server](https://webpack.github.io/docs/webpack-dev-server.html#api)
- [grunt connect](https://github.com/gruntjs/grunt-contrib-connect#base)
- [gulp connect](https://github.com/avevlad/gulp-connect#optionsroot)

Implementing this could be of great help to those migrating to rollup from other tools by minimizing the reworking a project may require.

**Comment by thgh** [comment]
Alright, good point @jdonaldson10, make sure to check out version 0.3.0 😃 

Thanks for bringing it up @mflux!

**Comment by jdonaldson10** [comment]
Looking good! :ok_hand:
