### ISSUE TITLE
Option to run the server with HTTPS protocol

### ISSUE THREAD

**Issue by karthilxg** [thgh/rollup-plugin-serve#10]
is there a way we can launch the host in `https` mode?

**Comment by thgh** [comment]
It doesn't seem that much work:

- [ ] Import `createServer` from https instead of http
- [ ] Pass the [certificate and key](https://webpack.js.org/configuration/dev-server/#devserver-https) as parameter
- [ ] Update default url

Would you like to implement this?

**Comment by karthilxg** [comment]
@thgh Yes!! Let me give it a try!!

**Comment by karthilxg** [comment]
@thgh I have done the changes for this feature, please verify.
https://github.com/thgh/rollup-plugin-serve/pull/12
