### ISSUE TITLE
Error when using this plugin: [!] TypeError: Cannot add property default_type, object is not extensible

### ISSUE THREAD

**Issue by SFantasy** [thgh/rollup-plugin-serve#100]
It's an error using the new version of mime. And mime@4.0.0 is just published.

Maybe this package should change dependency in package.json "mime: ">= 2.6.4" to "mime: "^2.6.4" or make it compatible with mime@4.0.0

**Comment by Frank3K** [comment]
Fixed in https://github.com/thgh/rollup-plugin-serve/pull/101 and released in 3.0.0. Can any of you (@SFantasy or @thgh) close this issue?
