### ISSUE TITLE
Code that handles favicon.ico specifically.

### ISSUE THREAD

**Issue by ananthb** [thgh/rollup-plugin-serve#20]
This particular behaviour should be documented so as to not catch the user by surprise. I did not add a favicon to my project and I certainly did not expect to see one when I hadn't explicitly added it.

I am also in favour of doing away with the code entirely. The benefits far out weight any potential shortcomings.

I would love to hear from the code author, rollup-plugin-serve contributors & users, and any other interested party on what exactly serving up a default favicon.ico brings to the table.

**Comment by thgh** [comment]
Sounds good to me!
