### ISSUE TITLE
Error on readFileFromContentBase with multiple content bases causes crash

### ISSUE THREAD

**Issue by chandlerprall** [thgh/rollup-plugin-serve#3]
When using this plugin with an array of content bases, if a request is made for a file that does not exist it can pass the array of content bases into `path.resolve` which expects a single string. This crashes and stops the server. https://github.com/thgh/rollup-plugin-serve/blob/master/src/index.js#L44

**Comment by thgh** [comment]
Thanks for reporting! I think it's fixed in v0.4.0
