### ISSUE TITLE
Rollup v1.0 compatibility

### ISSUE THREAD

**Issue by rkunev** [thgh/rollup-plugin-serve#31]
When using `rollup-plugin-serve` with rollup `^1.0.0` a deprecation warning is printed:
```
(!) serve plugin: The ongenerate hook used by plugin serve is deprecated. The generateBundle hook should be used instead.
```
Looks like `ongenerate` can be safely replaced by `generateBundle` [here](https://github.com/thgh/rollup-plugin-serve/blob/master/src/index.js#L87). Perhaps it's time to release `rollup-plugin-serve@1.0.0` too? This way the plugin won't break for users which don't plan to upgrade to `rollup@1`.

**Comment by thgh** [comment]
Thanks for letting me know!
