### ISSUE TITLE
HOT Module swapping 

### ISSUE THREAD

**Issue by frank-dspeed** [thgh/rollup-plugin-serve#36]
Some one maybe i should apply hot module swapping to this package.

**Comment by thgh** [comment]
You might be interested in https://github.com/thgh/rollup-plugin-livereload

Would be could if you could make a plugin that delivers HMR.

Related: https://github.com/rollup/rollup/issues/50 & https://github.com/PepsRyuu/nollup

**Comment by prantlf** [comment]
I use the two plugins together:

```js
serve({
  open: false,
  port: 8080,
  contentBase: __dirname,
  serveIndex: true,
}),
liveReload({
  watch: ['dist', 'pages'],
})
```

**Comment by frank-dspeed** [comment]
we can close that thanks for participation you helped me a lot
