### ISSUE TITLE
Got port error (EADDRINUSE) when launching a svelte app with rollup-serve on the same port (historyApiFallback)

### ISSUE THREAD

**Issue by witcher-development** [thgh/rollup-plugin-serve#51]
Hi! 
Actually all situation is explained in the title.

rollup.config.js
```
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import typescript from 'rollup-plugin-typescript2';
import image from '@rollup/plugin-image';
import { scss, typescript as typescriptPreprocess } from 'svelte-preprocess';
import alias from '@rollup/plugin-alias';
import serve from 'rollup-plugin-serve';

const production = !process.env.ROLLUP_WATCH;

export default {
	input: 'src/main.ts',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/bundle.js',
	},
	plugins: [
		alias({
			resolve: ['.js', '.ts'],
			entries: {
				assets: 'public/assets',
			},
		}),
		svelte({
			preprocess: [
				scss(),
				typescriptPreprocess({
					tsconfigFile: './tsconfig.json',
				}),
			],
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file — better for performance
			css: (css) => {
				css.write('public/bundle.css');
			},
		}),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration —
		// consult the documentation for details:
		// https://github.com/rollup/rollup-plugin-commonjs
		resolve({
			browser: true,
			dedupe: (importee) =>
				importee === 'svelte' || importee.startsWith('svelte/'),
		}),
		commonjs(),
		typescript(),

		image(),
		serve({
			contentBase: 'public',
			historyApiFallback: true,
			port: 5001,
		}),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload(),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser(),
	],
	watch: {
		clearScreen: false,
	},
};
```

index.html
```
<!doctype html>
<html>
<head>
	<meta charset='utf8'>
	<meta name='viewport' content='width=device-width'>

	<title>Svelte app</title>

	<link rel="icon" href="assets/favicon.ico">

	<link rel='stylesheet' href='/global.css'>
	<link rel='stylesheet' href='/bundle.css'>
</head>

<body>
	<script src='/bundle.js'></script>
</body>
</html>
```

folder structure
![image](https://user-images.githubusercontent.com/28788017/70270844-e0694d80-17ad-11ea-8eeb-04871973aeae.png)

![image](https://user-images.githubusercontent.com/28788017/70270679-9aac8500-17ad-11ea-81b4-09571646b85a.png)

At all, I am building a spa, but getting 404 when requesting non '/' routes. So I trying to achieve historyApiFallback work.

I will be grateful for any help!

**Comment by thgh** [comment]
> Your application is ready!

That line is printed by some other programm running on port 5001. It's not possible to run two programs on the same port. What command did you run for the last screenshot?

**Comment by witcher-development** [comment]
It was Svelte compiler. Exactly command was "rollup -c -w". Should they run on different ports?
When I start Svelte and rollup-serve on different ports historyApiFallback just doesn't work.
By the app flow, I geting to /login page according to client routing plugin, but then if I reload the page I get 404.
I thought it should run together on the same port, but obviously I don't understand the process.
How can I achieve the needed behavior? Thank you!

**Comment by thgh** [comment]
If the only command was `rollup -c -w` then I don't know what's going on. It looks like you are also running the `serve` package

**Comment by witcher-development** [comment]
Oh, sorry. Actually I was wrong.
Here are my npm scripts: 
![image](https://user-images.githubusercontent.com/28788017/70378727-86db5d00-192c-11ea-9194-3e55cae6d403.png)
(I started "dev")

And yes, I tried to launch serve plugin and my app on the same port. How to do it right?

**Comment by thgh** [comment]
This plugin replaces the `sirv` functionality in development, so change package.json:
```
  "dev": "rollup -c -w"
```

Also consider adding rollup-plugin-livereload => `livereload('public')`

**Comment by witcher-development** [comment]
Yes, now it works! Thank you very much!
