### ISSUE TITLE
Is this safe to use with multiple bundles

### ISSUE THREAD

**Issue by CrashyBang** [thgh/rollup-plugin-serve#52]
Hey,

I am using this with multiple bundles i.e:

```js
export default [
	{
                input: 'packages/A/index.js',
                plugins: [serve()],
		output: {
			name: '[name]Bundle',
			file: '[name].umd.js',
			format: 'umd'
		}
	},
	{
                input: 'packages/B/index.js',
                plugins: [serve()],
		output: {
			name: '[name]Bundle',
			file: '[name].umd.js',
			format: 'umd'
		}
	}
];
```

Now this all works as expected but I wanted to see if there are any issues calling `serve()` for each bundle?

I actually apply the plugins array dynamically in the actual project and if there is a performance concern associated with running `serve()` multiple times I can just run it on the first or last bundle to be built.

Cheers!

**Comment by thgh** [comment]
I'm not aware of a way to detect multiple `serve()` vs a reload due to rollup watch. So the current behaviour is to close the previous and start a new server everytime `serve()` is called.

What behaviour would you expect?

**Comment by CrashyBang** [comment]
Hey @thgh,

After thinking about it the behavior your describing is exactly what I would expect, I just didn't think it through correctly!

Cheers!
