### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by tomik23** [thgh/rollup-plugin-serve#62]
The problem occurs under windows 10.
I analyzed the code and this line `var urlPath = path.normalize (unsafePath);` there is a problem.

**Comment by thgh** [comment]
Ow sorry, please use v1.0.1 for now

**Comment by tomik23** [comment]
Yes I know I went back to v1.0.1
Thanks

**Comment by thgh** [comment]
Just released v1.0.3 and hope that it's fixed!

**Comment by tomik23** [comment]
I checked and now it works.
