### ISSUE TITLE
Add `onListening` hook

### ISSUE THREAD

**Issue by filoxo** [thgh/rollup-plugin-serve#68]
I don't know if this is something that the project would be interested in, so I'm opening this for discussion. I'd like to know if it might be good to provide an equivalent to webpack-dev-server's [`onListening`](https://webpack.js.org/configuration/dev-server/#devserveronlistening) hook. This simply executes a function once the server starts listening, doesn't do any middleware stuff. I use this at my current work to display the full entry URL of the application after it starts, which has been a nice-to-have for our internal dev experience. I'm open to creating a PR but I just wanted to check with you maintainers before I go down that route. Thanks!

**Comment by thgh** [comment]
PR welcome 😃

**Comment by filoxo** [comment]
Released in [v1.1.0](https://github.com/thgh/rollup-plugin-serve/blob/master/CHANGELOG.md#110---2020-11-01).
