### ISSUE TITLE
Using plugin serve with watch option

### ISSUE THREAD

**Issue by NoxWings** [thgh/rollup-plugin-serve#8]
I'm not sure if I'm using this incorrectly or it is a "bug". 
I'm trying to use this plugin with the watch option. The first time it runs ok, It looks like the socket is kept open. The second time I run the build it reports the port is already in use.

It only happens while using the watch option but it is completely fine without it.

Here is my rollup.config.js
```javascript
import commonjs from "rollup-plugin-commonjs";
import resolve from "rollup-plugin-node-resolve";
import babel from "rollup-plugin-babel";
import uglify from "rollup-plugin-uglify";
import serve from "rollup-plugin-serve";
import livereload from "rollup-plugin-livereload";


const DISTFOLDER = "dist";

export default {
    entry: "src/main.js",
    format: "iife",
    moduleName: "app",
    plugins: [
        resolve({ jsnext: true, main: true }),
        commonjs(),
        babel({ exclude: "node_modules/**" }),
        uglify(),
        serve({ contentBase: DISTFOLDER,  port: 8080 }),
        livereload({ watch: DISTFOLDER })
    ],
    external: [],
    dest: `${DISTFOLDER}/bundle.js`
};

```

**Comment by NoxWings** [comment]
I've just noticed something:

1.- Running `rollup -c` then Ctrl+C to stop the server. Works ok.
2.- Running `rollup -c -w` I have to Ctrl+C twice... but it works. The socket is freed.
3.- Running it through npm with `npm run dev` I only have to Ctrl+C once but the socket is not freed.
```
"scripts": {
    "dev": "rollup -c -w --sourcemap",
}
```

**Comment by thgh** [comment]
Thanks for reporting 😃 

I'm not sure how to fix it. PRs welcome!

**Comment by vinjoel** [comment]
Submitted a PR to close the server when termination signals are encountered

**Comment by andrejcremoznik** [comment]
What's the holdup for releasing this to npm?

**Comment by thgh** [comment]
Time ;-)

It has been [published](https://www.npmjs.com/package/rollup-plugin-serve).
