### ISSUE TITLE
Add `index.d.ts`

### ISSUE THREAD

**Issue by felipecrs** [thgh/rollup-plugin-serve#88]
Because otherwise VS Code warns about missing types declaration:

![image](https://user-images.githubusercontent.com/29582865/172894980-b4da3fff-18a7-4a6c-9eda-5f6c0ad08a0f.png)

**Comment by foretoo** [comment]
i created [pull request](https://github.com/thgh/rollup-plugin-serve/pull/89) related to this issue

**Comment by thgh** [comment]
Released in v2.0.0
