### ISSUE TITLE
Improvements to Type Definitions

### ISSUE THREAD

**Issue by tommy-mitchell** [thgh/rollup-plugin-serve#92]
Originally I came here to file a bug report. In `index.d.ts`, the `options.headers` property is declared using TypeScript's builtin [`Headers` interface][ts-headers], which is different from the intended [Node HTTP headers][node-headers]:

https://github.com/thgh/rollup-plugin-serve/blob/6743a314411d24c373329d61236e215b7af20b0a/index.d.ts#L53-L56

However, while looking into it, I noticed that many of the type descriptions were slightly different from those declared in `index.js` using JSDoc tags. The TypeScript compiler actually already has a way of [emitting type definitions from JS files][ts-jsdoc], which can use the plugin's already-maintained JSDoc tags (and their comment descriptions) to create an `index.d.ts` file. Using this method, types could be automatically created on build and would only have to be maintained in the one file.

I've tested this out on a local clone of the repo and it seems to work well. I'm happy to make a PR.

----

As an aside, the DefinitelyTyped definitions for Node HTTP includes a list of common headers, such as [this list for `IncomingHTTPHeaders`][dt-headers]. I'm not familiar with the types of headers used by this plugin, but by using these types IntelliSense can suggest the common headers[^1]:

```ts
import { IncomingHttpHeaders, OutgoingHttpHeaders } from 'http'

export interface ServeOptions {
  // ...
  
  headers?: IncomingHttpHeaders | OutgoingHttpHeaders | {
    // i.e. Parameters<OutgoingMessage["setHeader"]>
    [name: string]: number | string | ReadonlyArray<string>
  }
}
```

![image](https://user-images.githubusercontent.com/1403701/187055784-2315773a-2150-4bfd-a3b7-4912c8164299.png)

[ts-headers]: https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.headers.html
[node-headers]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts
[ts-jsdoc]: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
[dt-headers]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/827722371da23d8b93aeb71a2e0e02b049087ec0/types/node/http.d.ts#L47

[^1]: Using TypeScript here as I'm more familiar with the syntax than with JSDoc. Idea still applies.

**Comment by thgh** [comment]
Makes sense! PR welcome!

**Comment by richex-cn** [comment]
Just found this. Just what I need~

![Snipaste_2022-11-23_17-34-22](https://user-images.githubusercontent.com/25103518/203513181-07291dea-4289-47da-8ff5-61b3eb11b53b.png)

**Comment by thgh** [comment]
Lost track of this. I will merge the PR.

@richex-cn consider lowercasing the header
